apiVersion: v1
kind: Service
metadata:
  name: dockerizedmvcapp-service
spec:
  selector:
    app: dockerizedmvcapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

